# Generated by Django 2.1.3 on 2018-11-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='account',
        ),
    ]
