# Generated by Django 2.1.3 on 2018-11-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_remove_loginuser_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='account',
            field=models.CharField(default='001', max_length=150),
            preserve_default=False,
        ),
    ]
