# Generated by Django 2.1.3 on 2018-11-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_loginuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='data',
            field=models.FileField(default='q', upload_to='myfile'),
            preserve_default=False,
        ),
    ]
